Beehive_3_0_0_Beta1/src/org/openremote/beehive/api/dto/CodeDTO.java
/* OpenRemote, the Home of the Digital Home.
* Copyright 2008-2009, OpenRemote Inc.
*
* See the contributors.txt file in the distribution for a
* full listing of individual contributors.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
package org.openremote.beehive.api.dto;

import org.apache.commons.lang.StringUtils;

/**
 * Infrared Codes (arbitrary name-value pairs). Typically consists of string names mapped to infrared code hex values.
 * 
 * <pre>
 * For example:
 *    play	0x20
 *    plus	0xD0
 *    ffwd	0xE0
 *    rev	0x10
 *    minus	0xB0
 *    menu	0x40
 * </pre>
 * 
 * @author Dan 2009-2-6
 * @author allen.wei 2009-2-18
 */
@SuppressWarnings("serial")
public class CodeDTO extends BusinessEntityDTO {

   private String name;

   private String remoteName;

   private String value;

   private String comment;

   public CodeDTO() {
      value = "";
      remoteName = "";
      comment = "";
   }

   public String getName() {
      return name;
   }

   public void setName(String name) {
      this.name = name;
   }

   public String getValue() {
      return value;
   }

   public void setValue(String value) {
      this.value = value;
   }

   public String getComment() {
      return comment;
   }

   public void setComment(String comment) {
      this.comment = comment;
   }

   public boolean isBlankComment() {
      return StringUtils.isBlank(getComment());
   }

   public String getRemoteName() {
      return remoteName;
   }

   public void setRemoteName(String remoteName) {
      this.remoteName = remoteName;
   }
}

Beehive_3_0_0_Beta1/src/org/openremote/beehive/domain/SyncHistory.java
/* OpenRemote, the Home of the Digital Home.
* Copyright 2008-2009, OpenRemote Inc.
*
* See the contributors.txt file in the distribution for a
* full listing of individual contributors.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
package org.openremote.beehive.domain;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.openremote.beehive.utils.DateUtil;

/**
 * @author Tomsky
 *
 */
@Entity
@Table(name = "sync_history")
@SuppressWarnings("serial")
public class SyncHistory extends BusinessEntity {
   private Date startTime;
   private Date endTime;
   private String type;
   private String status;
   private String logPath;
   
   @Column(name = "start_time")
   public Date getStartTime() {
      return startTime;
   }
   @Column(name = "end_time")
   public Date getEndTime() {
      return endTime;
   }
   @Column(nullable = false)
   public String getType() {
      return type;
   }
   @Column(nullable = false)
   public String getStatus() {
      return status;
   }
   @Column(name = "log_path")
   public String getLogPath() {
      return logPath;
   }

   public void setStartTime(Date startTime) {
      this.startTime = startTime;
   }
   
   @Transient
   public String getStartDate() {
      return DateUtil.getDefaultFormat(startTime);
   }
   
   
   public void setEndTime(Date endTime) {
      this.endTime = endTime;
   }
   
   public void setType(String type) {
      this.type = type;
   }

   public void setStatus(String status) {
      this.status = status;
   }

   public void setLogPath(String logPath) {
      this.logPath = logPath;
   }

   public SyncHistory() {
      // TODO Auto-generated constructor stub
   }
}

Beehive_3_0_0_Beta1/src/org/openremote/beehive/controller/BeehiveDatabaseController.java
/* OpenRemote, the Home of the Digital Home.
* Copyright 2008-2009, OpenRemote Inc.
*
* See the contributors.txt file in the distribution for a
* full listing of individual contributors.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
package org.openremote.beehive.controller;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.openremote.beehive.api.dto.RemoteSectionDTO;
import org.openremote.beehive.api.service.CodeService;
import org.openremote.beehive.api.service.ModelService;
import org.openremote.beehive.api.service.RemoteOptionService;
import org.openremote.beehive.api.service.RemoteSectionService;
import org.openremote.beehive.api.service.VendorService;
import org.springframework.web.bind.ServletRequestBindingException;
import org.springframework.web.bind.ServletRequestUtils;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.multiaction.MultiActionController;

/**
 * Controller for Beehive database UI Interface User: allenwei Date: 2009-2-11 Time: 17:27:22
 */
public class BeehiveDatabaseController extends MultiActionController {

   private VendorService vendorService;
   private ModelService modelService;
   private RemoteSectionService remoteSectionService;
   private RemoteOptionService remoteOptionService;
   private CodeService codeService;

   public void setVendorService(VendorService vendorService) {
      this.vendorService = vendorService;
   }

   public void setModelService(ModelService modelService) {
      this.modelService = modelService;
   }

   public void setRemoteSectionService(RemoteSectionService remoteSectionService) {
      this.remoteSectionService = remoteSectionService;
   }

   public void setRemoteOptionService(RemoteOptionService remoteOptionService) {
      this.remoteOptionService = remoteOptionService;
   }

   public void setCodeService(CodeService codeService) {
      this.codeService = codeService;
   }

   private String index;
   private String cmpSelectContainer;
   private String cmpLircDetails;

   /**
    * Default method in controller
    * 
    * @param request
    *           HttpServletRequest
    * @param response
    *           HttpServletResponse
    * @return ModelAndView
    */
   public ModelAndView index(HttpServletRequest request, HttpServletResponse response) {
      ModelAndView mav = new ModelAndView(index);
      mav.addObject("vendors", vendorService.loadAllVendors());
      return mav;
   }

   /**
    * Show cmpSelectContainer page rendor select element as Model list
    * 
    * @param request
    *           HttpServletRequest
    * @param response
    *           HttpServletResponse
    * @return ModelAndView
    * @throws ServletRequestBindingException
    *            Exception occured when missing vendor id parameter
    */
   public ModelAndView showModelSelect(HttpServletRequest request, HttpServletResponse response)
         throws ServletRequestBindingException {
      ModelAndView mav = new ModelAndView(cmpSelectContainer);
      String generateSelectTcagId = ServletRequestUtils.getRequiredStringParameter(request, "generateSelectTcagId");
      long vendorId = ServletRequestUtils.getRequiredLongParameter(request, "vendorId");
      mav.addObject("items", modelService.findModelsByVendorId(vendorId));
      mav.addObject("generateSelectTcagId", generateSelectTcagId);
      return mav;

   }

   /**
    * Show cmpSelectContainer page rendor select element as remoteSection list
    * 
    * @param request
    *           HttpServletRequest
    * @param response
    *           HttpServletResponse
    * @return ModelAndView
    * @throws ServletRequestBindingException
    *            Exception occured when missing model id parameter
    */
   public ModelAndView showRemoteSelect(HttpServletRequest request, HttpServletResponse response)
         throws ServletRequestBindingException {
      ModelAndView mav = new ModelAndView(cmpSelectContainer);
      String generateSelectTcagId = ServletRequestUtils.getRequiredStringParameter(request, "generateSelectTcagId");
      long modelId = ServletRequestUtils.getRequiredLongParameter(request, "modelId");
      mav.addObject("items", remoteSectionService.findByModelId(modelId));
      mav.addObject("generateSelectTcagId", generateSelectTcagId);
      return mav;
   }

   /**
    * Show LIRC details page according to Model
    * 
    * @param request
    *           HttpServletRequest
    * @param response
    *           HttpServletResponse
    * @return ModelAndView
    * @throws ServletRequestBindingException
    *            Exception occured when missing model id parameter
    */
   public ModelAndView showLircDetailByModel(HttpServletRequest request, HttpServletResponse response)
         throws ServletRequestBindingException {
      ModelAndView mav = new ModelAndView(cmpLircDetails);
      long modelId = ServletRequestUtils.getRequiredLongParameter(request, "modelId");
      RemoteSectionDTO remoteSectionDTO = remoteSectionService.loadFisrtRemoteSectionByModelId(modelId);
      mav.addObject("model", modelService.loadModelById(modelId));
      mav.addObject("section", remoteSectionDTO);
      mav.addObject("options", remoteOptionService.findByRemoteSectionId(remoteSectionDTO.getOid()));
      mav.addObject("codes", codeService.findByRemoteSectionId(remoteSectionDTO.getOid()));
      return mav;
   }

   /**
    * Show LIRC details page according to remoteSection
    * 
    * @param request
    *           HttpServletRequest
    * @param response
    *           HttpServletResponse
    * @return ModelAndView
    * @throws ServletRequestBindingException
    *            Exception occured when missing section id parameter
    */
   public ModelAndView showLircDetailByRemoteSection(HttpServletRequest request, HttpServletResponse response)
         throws ServletRequestBindingException {
      ModelAndView mav = new ModelAndView(cmpLircDetails);
      long sectionId = ServletRequestUtils.getRequiredLongParameter(request, "sectionId");
      mav.addObject("model", remoteSectionService.loadModelById(sectionId));
      mav.addObject("section", remoteSectionService.loadSectionById(sectionId));
      mav.addObject("options", remoteOptionService.findByRemoteSectionId(sectionId));
      mav.addObject("codes", codeService.findByRemoteSectionId(sectionId));
      return mav;
   }

   /**
    * Return if this model has multi-remoteSection
    * 
    * @param request
    *           HttpServletRequest
    * @param response
    *           HttpServletResponse
    * @return ModelAndView
    * @throws IOException
    *            IOException
    * @throws ServletRequestBindingException
    *            Exception occured when missing model id parameter
    */
   public ModelAndView isMutiSection(HttpServletRequest request, HttpServletResponse response) throws IOException,
         ServletRequestBindingException {
      long modelId = ServletRequestUtils.getRequiredLongParameter(request, "modelId");
      response.getWriter().print(remoteSectionService.findByModelId(modelId).size() > 1);
      return null;
   }

   public void setIndex(String index) {
      this.index = index;
   }

   public void setCmpSelectContainer(String cmpSelectContainer) {
      this.cmpSelectContainer = cmpSelectContainer;
   }

   public void setCmpLircDetails(String cmpLircDetails) {
      this.cmpLircDetails = cmpLircDetails;
   }
}

Beehive_3_0_0_Beta1/web/WEB-INF/page/beehiveDatabase.jsp
<%--
  User: allenwei
  Date: 2009-2-11
  Time: 17:36:57
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../../common/taglibs.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Beehive Database</title>
    <link href="image/OpenRemote_Logo16x16.png" rel="shortcut icon"/>
    <link href="image/OpenRemote_Logo16x16.png" type="image/png" rel="icon"/>
    <link type="text/css" href="css/openremote_base.css" rel="stylesheet"/>
    <link type="text/css" href="css/beehiveDatabase.css" rel="stylesheet"/>
    <script type="text/javascript" src="jslib/jquery-1.3.1.min.js"></script>
    <script type="text/javascript" src="js/beehiveDatabase.js"></script>
</head>
<body>
<div id="main">
    <div id="title">
        <h1>Beehive Database</h1>
    </div>
    <div id="undecoratedLink">
        [
        <a class="regularLink" target="" href="changes.htm" title="Administration">
            Administration
        </a>
        ]
    </div>
    <div id="content">
        <div class="content_head">
            <h2>Browse LIRC database</h2>
        </div>
        <div id="content_body">
            <div id="lirc_select">
                <div id="vendor_select_container" class="lirc_select_container">
                    <div class="select_container_title">
                        <h3>Select device vendor:</h3>
                    </div>
                    <div class="select_container_head">
                        <input class="filter_input" type="text" value="Filter..." tabindex="1"/>
                        <button class="buttonNonpersistent resetBtn">Reset</button>
                    </div>
                    <div class="select_wrapper">
                        <select id="vendor_select" multiple="multiple" size="8"
                                onchange="showSelect(this.id,this.options[this.selectedIndex].value)">
                            <option value="0">------------</option>
                            <c:forEach items="${vendors}" var="vendor">
                                <option value="${vendor.oid}">${vendor.name}</option>
                            </c:forEach>
                        </select>
                    </div>
                </div>
                <div id="model_select_container" class="lirc_select_container" style="display:none">
                    <div class="select_container_title">
                        <h3>Select device model:</h3>
                    </div>
                    <div class="select_container_head">
                        <input type="text" value="Filter..." class="filter_input" tabindex="1"/>
                        <button class="buttonNonpersistent resetBtn">Reset</button>
                    </div>
                    <div class="select_wrapper">
                    </div>
                </div>
                <div id="section_select_container" class="lirc_select_container" style="display:none">
                    <div class="select_container_title">
                        <h3>Select device section:</h3>
                    </div>
                    <div class="select_container_head">
                        <input type="text" value="Filter..." class="filter_input" tabindex="1"/>
                        <button class="buttonNonpersistent resetBtn">Reset</button>
                    </div>
                    <div class="select_wrapper">
                    </div>
                </div>

            </div>
            <div class="clear"></div>
            <div id="lirc_details_container" style="display:none;"></div>
        </div>
    </div>

</div>

<div id="waiting_div" style="display: none;">
	<img src="image/statusindicator.gif" alt="wating" />
</div>
</body>
</html>

Beehive_3_0_0_Beta1/web/WEB-INF/page/breadcrumb.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../../common/taglibs.jsp" %>
<div id="breadcrumbs">
<c:set var="breadcrumb" value='${fn:split(breadcrumbPath,"/")}'></c:set>
<a class="path_t" href="history.htm"><span class="path_text">Beehvie</span></a>
<span class="path_t">/</span>
<c:set var="getModelsUrl" value='history.htm?method=getModels&path='></c:set>
<c:set var="getContentUrl" value='history.htm?method=getContent&path='></c:set>

<c:choose>
	<c:when test="${param.isFile}">
		<c:forEach items='${breadcrumb}' var="name" varStatus="status">
		   <c:if test='${status.count lt fn:length(breadcrumb)}'>
		      <a class="" href="${getModelsUrl}${fn:substring(breadcrumbPath, 0,fn:indexOf(breadcrumbPath,name)+fn:length(name))} ">${name}</a>
		   </c:if>
		   <c:if test='${status.count lt fn:length(breadcrumb)}'>
		      <span class="path_t">/</span>
		   </c:if>
		   <c:if test="${status.count eq fn:length(breadcrumb)}">     
            <a class="" href="${getContentUrl}${breadcrumbPath}">${name}</a>
         </c:if>
		</c:forEach>
	</c:when>
	<c:otherwise><!-- is dir -->
	   <c:forEach items='${breadcrumb}' var="name" varStatus="status">
         <c:if test='${status.count le fn:length(breadcrumb)}'>
            <a class="noClass" href="${getModelsUrl}${fn:substring(breadcrumbPath, 0,fn:indexOf(breadcrumbPath,name)+fn:length(name))} ">${name}</a>
         </c:if>
         <c:if test='${status.count lt fn:length(breadcrumb)}'>
            <span class="path_t">/</span>
         </c:if>
      </c:forEach>
	</c:otherwise>
</c:choose>
</div>

Beehive_3_0_0_Beta1/web/WEB-INF/page/cmpLircDetails.jsp
<%@ include file="../../common/taglibs.jsp" %>
<jsp:useBean id="commonUtils" class="org.apache.commons.lang.StringUtils"/>
<div>
<button onclick="window.open('lirc.html?method=export&id=${model.oid}')"
	class="buttonNonpersistent">Download LIRC configuration file</button>
</div>
<div id="lirc_details_title" class="content_head">
    LIRC File Details
</div>
<div class="lirc_entry">
    <div class="label">Selected LIRC file:</div>
    <div class="output">${model.fileName}</div>
</div>
<div class="lirc_entry">
    <div class="label">Model:</div>
    <div class="output">${model.name}</div>
</div>
<div class="lirc_entry">
    <div class="label">Supported devices:</div>
    <div class="output">UNKNOWN</div>
</div>
<div id="lirc_comment" class="more_detail_container">
    <div class="detail_title">
        Comments
    </div>
    <div class="detail_content">
        <pre>${section.comment}</pre>
    </div>
</div>

<div class="lirc_entry">
    <div class="label">Selected remote:</div>
    <div class="output">${options[0].value}</div>
</div>
<div class="lirc_entry">
    <div class="label">Flags:</div>
    <div class="output">${options[2].value}</div>
</div>
<div id="lirc_code_option" class="more_detail_container">
    <div class="detail_title">
        Infrared Code Options
    </div>
    <div class="detail_content">
        <table class="data_table">
            <tbody>
            <c:forEach items="${options}" var="option" varStatus="n">
                <c:if test="${!option.blankComment}">
                    <tr class="comment_row">
                        <td colspan="2">
                            <pre>${option.comment}</pre>
                        </td>
                    </tr>
                </c:if>
                <tr>
                    <td class="twentyPercentColumn">${option.name}</td>
                    <td class="defaultColumn">${option.value}</td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>
</div>
<br/>

<div id="lirc_codes" class="more_detail_container">
    <div class="detail_title">
        Infrared Codes
    </div>
    <div class="detail_content">
        <table class="data_table">
            <tbody>
            <c:forEach items="${codes}" var="code">
                  <c:if test="${!code.blankComment}">
                    <tr class="comment_row">
                        <td colspan="2">
                            <pre>${code.comment}</pre>
                        </td>
                    </tr>
                </c:if>
                <tr>
                    <td class="twentyPercentColumn">${code.name}</td>
                    <td class="defaultColumn wrapWhitespace">
                        <pre>${code.value}</pre>
                    </td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>
</div>

<div id="bottom">
    <button onclick="window.open('lirc.html?method=export&id=${model.oid}')" class="buttonNonpersistent">Download LIRC configuration file
    </button>
</div>

Beehive_3_0_0_Beta1/web/WEB-INF/page/cmpSelectContainer.jsp
<%@ include file="../../common/taglibs.jsp" %>

<select id="${generateSelectTcagId}" multiple="multiple" size="8"
        onchange="showSelect(this.id,this.options[this.selectedIndex].value)">
    <option value="0">------------</option>
    <c:forEach items="${items}" var="item">
        <option value="${item.oid}">${item.name}</option>
    </c:forEach>
</select>

Beehive_3_0_0_Beta1/web/WEB-INF/page/fileContent.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../../common/taglibs.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <link href="css/default.css" type="text/css" rel="stylesheet" media="screen">
   <script type="text/javascript" src="jslib/jquery-1.3.1.min.js"></script>
   <title>OpenRemote Beehive - File Comparison With Latest Revision</title>
</head>
<body tabId="3">
   <table class="infopanel" width="100%" border="0" cellpadding="0"
      cellspacing="0">
         <tr>
            <td>
            <table width="100%" border="0" cellpadding="0" cellspacing="0">
                  <tr class="path_node">
                     <td nowrap="true"><span class="pathFormat">
                     Path&nbsp;:&nbsp; </span></td>
                     <td width="100%" nowrap="true">
                        <jsp:include page="breadcrumb.jsp" flush="true">
                           <jsp:param name="breadcrumbPath" value="${breadcrumbPath}" />
                           <jsp:param name="isFile" value="true" />
                        </jsp:include>
                     </td>
                  </tr>
            </table>
            </td>
         </tr>
         <tr>
            <td width="100%">
               <table class="tabcontent" width="100%" border="0" cellpadding="0"
                  cellspacing="0">
                     <tr class="value" nowrap="true">
                        <td class="value" style="padding-left: 20px;" nowrap="true"><b>Revision:</b>&nbsp;
                           <a href="#">
                           ${modelMessage.revision} </a></td>                   
                        <td class="value" style="padding-left: 20px;" nowrap="true"><b>Author:</b>&nbsp;
                            ${modelMessage.author}</td>
                        <td width="100%"></td>
                     </tr>
                     <tr>
                        <td class="value" style="padding-left: 20px;" colspan="5"
                           width="100%"><b>Comment:</b>&nbsp; ${modelMessage.comment}</td>
                     </tr>
               </table>
            </td>
            <td>
            <table class="tabcontent" border="0" cellpadding="0" cellspacing="0">
                  <tr>
                     <td width="23" align="left" style="padding-right: 7px;"><a
                        href="history.htm?method=getRevisions&path=${breadcrumbPath}"><img src="image/revision.gif"
                        alt="File Revision list" title="File Revision list" border="0"></a>
                     </td>
                  </tr>
            </table>
            </td>
         </tr>
   </table>
   <table id="table_list_of_compare" rules="all" width="100%" border="0" cellpadding="0" cellspacing="0">
      <tr>         
         <td width="50%">
            <div id="right_div" style="height:500px">
               <table valign="top" width="100%" cellpadding="0" cellspacing="0">
                  <c:forEach items="${lines}" var="line" varStatus="status">
                  <tr valign="middle">
                     <td class="diffLineNumber"><a class="number" name="1" href="#1">${status.count } </a></td>
                     <td class="diffLine_N" width="100%" align="left" nowrap="true" "><pre>${line}</pre></td>
                  </tr>
                  </c:forEach>
               </table>
              </div>
             </td>
      </tr>
   </table>
</body>
</html>

Beehive_3_0_0_Beta1/web/WEB-INF/page/sync.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../../common/taglibs.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">   
   <title>OpenRemote Beehive - Changes From Update</title>
   <script type="text/javascript" src="js/progress.js"></script>
   <script type="text/javascript">
   $(document).ready(function() {	   
	   if($('#commitStatus').val() == "running"){
           $('#message').text(" The committing is running, please update later.");
           $("#updateBtn").attr("disabled","true").addClass("disabled_button");
     }
	   if($('#updateStatus').val() == "running"){
		   setAnimation();
		   var progress = new Progress({'type':'update', 'interval':5000, 'showMethod':showProgress, 'endMethod': endAnimation});
		   progress.show();
         progress.refresh();
		   $('#message').text("Updating form http://lirc.sourceforge.net/remotes ......");
	   }
	   $('#updateBtn').click(function(){
		      setAnimation();
			   $.post("sync.htm?method=update",{});
			   new Progress({'type':'update', 'interval':5000, 'showMethod':showProgress, 'endMethod': endAnimation}).refresh();
			   $('#message').text("Updating from http://lirc.sourceforge.net/remotes ......");
	      });
	 });
   
	function showProgress(progress){
		$('#updateInfo').html("<pre>"+progress.data+"</pre>");
		var infoContainer = $("#infoContainer");
		infoContainer[0].scrollTop = infoContainer[0].scrollHeight;
		var bar = $('#progressbar');
      bar.find('.progress').css("width",progress.percent);
      bar.find('.text').text(progress.percent);
	}
	function endAnimation(){
		$('#tab_2 img').attr("src","image/update_icon.gif");
      $('#updateBtn').removeAttr("disabled").removeClass("disabled_button");
      $('#spinner').hide();
      $('#message').html("Update completed, you can view and commit the <b><a href='changes.htm' style='text-decoration: underline;'>changes</a></b>");
	}	
	function setAnimation(){
		$('#tab_2 img').attr("src","image/update.gif");
      $('#updateBtn').attr("disabled","true").addClass("disabled_button");
      $('#spinner').show();
	}
</script>
</head>
	<body tabId="2">
	<table class="infopanel" width="100%" border="0" cellpadding="0"
		cellspacing="0">	
			<tr>
				<td width="100%">
				<table class="tabcontent" width="100%" border="0" cellpadding="0"
					cellspacing="0">
					   <tr>
					      <td colspan="5" style="padding-left: 20px;" class="value"><b>Last update:</b></td>
                     <td colspan="5" class="value">
                        <c:choose>
                           <c:when test="${lastUpdate ne null}">
			                     ${lastUpdate.startDate}&nbsp;(${lastUpdate.status })
                           </c:when>
                           <c:otherwise>
                              There is no sync yet.
                           </c:otherwise>
                        </c:choose>
                     </td>
                     <td></td>
                  </tr>
						<tr>
							<td class="value" style="padding-left: 20px;" colspan="5"
								width="10%"><b>Progress</b>&nbsp;:</td>
							<td class="value" colspan="5" width="80%">
								<div id="progressbar" style="float:left">
									<div class="text">0%</div>
									<div class="progress" >
									<span class="text" >0%</span>
									</div>
								</div><span id="message" style="margin-left:10px">Please click the update button to sync lirc files with lirc website.</span>
							</td>
							<td class="value" colspan="5" width="10%"><input id="updateBtn" value="Update" class="button" type="button">
							</td>
						</tr>
				</table>
				</td>	
			</tr>			
	</table>
	<div id="infoContainer" class="infoContainer">
	   <div id="updateInfo"></div>
	   <div id="spinner"><img alt="" src="image/spinner.gif" /></div>
	</div>

</body>
</html>